site_name: html2pdf
site_description: A REST API that converts HTML files to PDF.
repo_url: https://github.com/YauheniSobaleu/html2pdf
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/YauheniSobaleu">YauheniSobaleu</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
